#!/bin/env python
import re,argparse,os
from pyexpander.lib import expandToStr

parser = argparse.ArgumentParser(description="PXBF Brainfuck expander")
parser.add_argument('file',help="Input file to expand")

args = parser.parse_args()
non_bf_chars = re.compile(r'[^+\-.,\[\]<>]')
try:
    with open(args.file,'r') as infile:
        with open(args.file.replace(".pxbf",".bf"),'w') as outfile:
            outfile.write(non_bf_chars.sub('', expandToStr(infile.read(),filename=args.file)[0]))
except Exception as e:
    os.unlink(args.file.replace(".pxbf",".bf"))
    raise e
